### ISSUE TITLE
ValueError: The two structures don't have the same number of elements

### ISSUE THREAD

**Issue by geolvr** [NivNayman/ConvGRU2D#1]
I run "ConvGRU2D/examples/bidirectional_conv_gru.py"  (copied to "/home/xxx/Desktop/ConvGRUtestNivNayman/test.py")
I got:

Traceback (most recent call last):
  File "/home/xxx/Desktop/ConvGRUtestNivNayman/test.py", line 19, in <module>
    input_shape=(None, 40, 40, 1), merge_mode='sum'))
  File "/home/xxx/tensorflow/lib/python3.5/site-packages/keras/models.py", line 497, in add
    layer(x)
  File "/home/xxx/tensorflow/lib/python3.5/site-packages/keras/layers/wrappers.py", line 325, in __call__
    return super(Bidirectional, self).__call__(inputs, **kwargs)
  File "/home/xxx/tensorflow/lib/python3.5/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/xxx/tensorflow/lib/python3.5/site-packages/keras/layers/wrappers.py", line 403, in call
    y = self.forward_layer.call(inputs, **kwargs)
  File "/home/xxx/tensorflow/lib/python3.5/site-packages/keras/layers/convolutional_recurrent.py", line 1513, in call
    initial_state=initial_state)
  File "/home/xxx/tensorflow/lib/python3.5/site-packages/keras/layers/convolutional_recurrent.py", line 376, in call
    input_length=timesteps)
  File "/home/xxx/tensorflow/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2771, in rnn
    swap_memory=True)
  File "/home/xxx/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3096, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/xxx/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2874, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/xxx/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2836, in _BuildLoop
    nest.assert_same_structure(list(packed_vars_for_body), list(body_result))
  File "/home/xxx/tensorflow/lib/python3.5/site-packages/tensorflow/python/util/nest.py", line 266, in assert_same_structure
    % (len_nest1, nest1, len_nest2, nest2))
ValueError: The two structures don't have the same number of elements.

First structure (4 elements): [<tf.Tensor 'bidirectional_1/while/Identity:0' shape=() dtype=int32>, <tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x7f90e8c1c668>, <tf.Tensor 'bidirectional_1/while/Identity_2:0' shape=(?, 40, 40, 40) dtype=float32>, <tf.Tensor 'bidirectional_1/while/Identity_3:0' shape=(?, 40, 40, 40) dtype=float32>]

Second structure (3 elements): [<tf.Tensor 'bidirectional_1/while/add_6:0' shape=() dtype=int32>, <tensorflow.python.util.tf_should_use._add_should_use_warning.<locals>.TFShouldUseWarningWrapper object at 0x7f90ae04e860>, <tf.Tensor 'bidirectional_1/while/add_5:0' shape=(?, 40, 40, 40) dtype=float32>]

------------------------
I use Tensorflow-gpu 1.6.0 and python 3.5.2.  I really need a Convolutional-GRU layer but I don't know what went wrong.

**Comment by habtamufanta** [comment]
Facing the same issue. Has someone got a resolve?

**Comment by qihuanwuqi** [comment]
I have the same question with you. Do you have the answer about this?

**Comment by qihuanwuqi** [comment]
Facing the same issue. Has someone got a resolve?
